# device_type is derived by parsing the user-agent string
device_type:
  default: web
  rules:
    - regex: spider|crawl|slurp|bot
      value: bot
    - regex: iPhone
      value: ios

# prefix is derived by parsing the request URI
prefix:
  default: "" # Empty string
  rules:
    - regex: ^/$
      value: /
    - value: /admin  # Implicit regex adds start anchor ^ to value
    - value: /api

# Define specific histograms for a given metric and label set
histogram_rules:
  - metric: time
    name: time
    labels:
      host: ^(www\.example\.com|www\.example2\.com)
      scheme: https
  - metric: time
    name: time_prefix
    labels:
      host: ^www\.example\.com
      scheme: https
      prefix: .*
  - metric: length
    name: length
    labels:
      host: ^(www\.example\.com|www\.example2\.com)
      scheme: https
